export const BHASHINI_LANGUAGES = [
  { code: 'hi-IN', bhashiniCode: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'en-IN', bhashiniCode: 'en', name: 'English', nativeName: 'English' },
  { code: 'bn-IN', bhashiniCode: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te-IN', bhashiniCode: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr-IN', bhashiniCode: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta-IN', bhashiniCode: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu-IN', bhashiniCode: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn-IN', bhashiniCode: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml-IN', bhashiniCode: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa-IN', bhashiniCode: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'or-IN', bhashiniCode: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'as-IN', bhashiniCode: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'mai-IN', bhashiniCode: 'mai', name: 'Maithili', nativeName: 'मैथिली' },
  { code: 'sat-IN', bhashiniCode: 'sat', name: 'Santali', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ' },
  { code: 'ks-IN', bhashiniCode: 'ks', name: 'Kashmiri', nativeName: 'کٲشُر / कश्मीरी' },
  { code: 'ne-IN', bhashiniCode: 'ne', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'gom-IN', bhashiniCode: 'gom', name: 'Konkani', nativeName: 'कोंकणी' },
  { code: 'sd-IN', bhashiniCode: 'sd', name: 'Sindhi', nativeName: 'سنڌي / सिंधी' },
  { code: 'doi-IN', bhashiniCode: 'doi', name: 'Dogri', nativeName: 'डोगरी' },
  { code: 'mni-IN', bhashiniCode: 'mni', name: 'Manipuri', nativeName: 'मৈতৈলোন্' },
  { code: 'brx-IN', bhashiniCode: 'brx', name: 'Bodo', nativeName: 'बड़ो' },
  { code: 'sa-IN', bhashiniCode: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्' },
  { code: 'ur-IN', bhashiniCode: 'ur', name: 'Urdu', nativeName: 'اردو' }
];
