import io
import base64
import edge_tts

class TTSService:
    @staticmethod
    async def text_to_speech(text: str, language_code: str) -> str:
        primary = language_code.split('-')[0].lower()
        
        # Mapping all 12 Indian languages to Microsoft Neural voices
        # including pa-IN-OjasviNeural for Punjabi and or-IN-SubhasiniNeural for Odia
        voice_map = {
            "hi": "hi-IN-SwaraNeural",
            "pa": "pa-IN-OjasviNeural",
            "bn": "bn-IN-BashkarNeural",
            "te": "te-IN-MohanNeural",
            "mr": "mr-IN-ManoharNeural",
            "ta": "ta-IN-ValluvarNeural",
            "gu": "gu-IN-NiranjanNeural",
            "kn": "kn-IN-SapnaNeural",
            "ml": "ml-IN-MidhunNeural",
            "or": "or-IN-SubhasiniNeural",
            "ur": "ur-IN-SalmanNeural",
            "en": "en-IN-NeerjaNeural"
        }
        
        voice = voice_map.get(primary, "en-IN-NeerjaNeural")
        
        communicate = edge_tts.Communicate(text, voice)
        audio_data = io.BytesIO()
        
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                audio_data.write(chunk["data"])
                
        audio_bytes = audio_data.getvalue()
        if not audio_bytes:
            raise Exception("No audio generated by Edge TTS")
            
        audio_base64 = base64.b64encode(audio_bytes).decode("utf-8")
        return audio_base64
