import { jsPDF } from "jspdf";
import "jspdf-autotable";

export const generateConsultationSlip = (patientProfile, consultationData, selectedLanguage) => {
  const doc = new jsPDF('p', 'pt', 'a4');
  
  // Header Branding
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(5, 150, 105); // Emerald 600
  doc.text("SehatMitra-AI", 40, 50);
  
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42); // Slate 900
  doc.text("Clinical Triage & Doctor Consultation Slip", 40, 72);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139); // Slate 500
  doc.text(`Generated: ${new Date().toLocaleString('en-IN')}`, 40, 90);
  doc.text(`Consultation Language: ${selectedLanguage?.name || 'English'}`, 40, 103);
  
  // Divider
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(1.5);
  doc.line(40, 115, 555, 115);

  // Section 1: Patient Details Table
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("Patient Medical Profile", 40, 135);

  doc.autoTable({
    startY: 145,
    head: [['Patient ID', 'Full Name', 'Age / Gender', 'Blood Group']],
    body: [
      [
        patientProfile?.patient_id || 'N/A',
        patientProfile?.full_name || 'Guest Patient',
        `${patientProfile?.age || '-'} Yrs / ${patientProfile?.gender || '-'}`,
        patientProfile?.blood_group || '-'
      ]
    ],
    theme: 'grid',
    headStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42], fontStyle: 'bold' },
    bodyStyles: { textColor: [51, 65, 85] },
    margin: { left: 40, right: 40 }
  });

  // Section 2: Address & Medical History
  doc.autoTable({
    startY: doc.lastAutoTable.finalY + 8,
    head: [['Chronic Conditions', 'Known Allergies', 'Location / Village']],
    body: [
      [
        Array.isArray(patientProfile?.chronic_conditions) && patientProfile.chronic_conditions.length > 0 
          ? patientProfile.chronic_conditions.join(', ') 
          : 'None reported',
        Array.isArray(patientProfile?.allergies) && patientProfile.allergies.length > 0 
          ? patientProfile.allergies.join(', ') 
          : 'None reported',
        `${patientProfile?.village_town || ''} ${patientProfile?.district || ''}`.trim() || 'Not specified'
      ]
    ],
    theme: 'plain',
    headStyles: { fontStyle: 'bold', textColor: [15, 23, 42] },
    margin: { left: 40, right: 40 }
  });

  // Section 3: Triage Risk Level Banner
  const nextY = doc.lastAutoTable.finalY + 25;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("AI Triage Evaluation", 40, nextY);

  const riskColors = {
    'Emergency': [220, 38, 38], // Red
    'High': [234, 88, 12],      // Orange
    'Moderate': [202, 138, 4],  // Amber
    'Low': [5, 150, 105]        // Emerald
  };
  const tier = consultationData?.risk_tier || 'Moderate';
  const color = riskColors[tier] || [71, 85, 105];

  doc.setFillColor(color[0], color[1], color[2]);
  doc.roundedRect(40, nextY + 10, 515, 28, 4, 4, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.text(`Triage Urgency Level: ${tier.toUpperCase()}`, 55, nextY + 28);

  // Section 4: Symptoms & AI Recommendation
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Reported Symptoms / Chief Complaint:", 40, nextY + 60);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(51, 65, 85);
  const symptomsText = doc.splitTextToSize(consultationData?.symptoms || 'Symptoms recorded in triage interview.', 515);
  doc.text(symptomsText, 40, nextY + 75);

  const recY = nextY + 75 + (symptomsText.length * 13) + 15;
  doc.setFont("helvetica", "bold");
  doc.setTextColor(15, 23, 42);
  doc.text("Clinical Observations & Recommended Action:", 40, recY);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(51, 65, 85);
  const recText = doc.splitTextToSize(consultationData?.recommendation || 'Consult your Primary Health Centre (PHC) medical officer for clinical examination.', 515);
  doc.text(recText, 40, recY + 15);

  // Footer Disclaimer
  doc.setFontSize(7.5);
  doc.setTextColor(148, 163, 184);
  doc.text("IMPORTANT NOTICE: This document is generated by an automated clinical triage assistant (SehatMitra-AI) for preliminary screening.", 40, 785);
  doc.text("It is NOT a formal prescription or medical diagnosis. Please present this summary to a qualified doctor or healthcare worker.", 40, 797);

  // Trigger browser download
  const filename = `SehatMitra_${patientProfile?.patient_id || 'Slip'}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
};
